### ISSUE TITLE
WASM dependencies should only be required on WASM

### ISSUE THREAD

**Issue by justinlovinger** [chemicstry/wasm_thread#28]
As is, using `wasm_thread` for native builds will result in compiling several unnecessary dependencies. `[dependencies]` should be replaced with `[target.'cfg(target_arch = "wasm32")'.dependencies]`, and probably similar for `[dev-dependencies]`.

**Comment by chemicstry** [comment]
Fixed in https://github.com/chemicstry/wasm_thread/commit/e5f89634c697d67aa265f371bcec7fd8d24282a9, thanks for reporting
