### ISSUE TITLE
Workaround for `is_finished`?

### ISSUE THREAD

**Issue by zdimension** [chemicstry/wasm_thread#30]
Are there any plans for supporting the `is_finished` method like on std's `JoinHandle`? I'm currently using a one-shot channel as a work-around, not sure if there is a cleaner way.

**Comment by zdimension** [comment]
I forked the repo and added the function [here](https://github.com/chemicstry/wasm_thread/commit/d4f6fb103132d5a3131856e65b05798ee1f0320c). Tested locally and it works. I have another commit on my branch since I had to rollback the wasm-bindgen dep to 0.2.93 because of a regression on their end. If you want I can cherry pick my `is_finished` commit and make a PR.

**Comment by chemicstry** [comment]
Sure, make a PR and I will merge it right away

**Comment by zdimension** [comment]
Fixed in #31
