### ISSUE TITLE
Futures created with `wasm_bindgen_futures::spawn_local` don't get executed

### ISSUE THREAD

**Issue by felipellrocha** [chemicstry/wasm_thread#6]
I'm spinning a thread using `wasm_thread`. Inside of it, I'm running some async functions inside of a `wasm_bindgen_futures::spawn_local` as such:

```rs
wasm_thread::spawn(move || {
  log::info!("1: spawn");
  while Ok(message) = channel_receiver.recv() {
    log::info!("2: message {:?}", &message);
    wasm_bindgen_futures::spawn_local(async move {
      log::info!("3: am i here?");
      download.asset().await;
    })
  }
});
```
Problem is that neither the 3rd `log::info!()` nor the `download.asset().await` get called.

Any idea why?

**Comment by chemicstry** [comment]
Could you be blocking browser's main thread event loop? In order for worker to spawn you either have to return from js->rust call or await on async function, so it allows browser event loop to continue.

**Comment by chemicstry** [comment]
I think the problem here might be the `channel_receiver.recv()`. What kind of channel is that? Try using an async one

**Comment by felipellrocha** [comment]
It's a crossbeam channel. This is on a spawned thread, so it shouldn't impact the main thread no? Also, this code worked fine previously in the main thread. In addition, the documentation on `spawn_local` leads me to believe the async I spawned would run in the spawned thread, not the main thread: https://docs.rs/wasm-bindgen-futures/0.4.31/wasm_bindgen_futures/fn.spawn_local.html

**Comment by chemicstry** [comment]
I might not have explained it well, but what I said also applies to the worker event loop. I haven't used wasm for a while now, so don't remember all the quirks.

The docs for `spawn_local` say `The future will always be run on the next microtask tick`. However, the worker can never execute next microtask tick because it is blocked on crossbeam channel `recv()`.

**Comment by felipellrocha** [comment]
I have modified it to this:
```rs
wasm_thread::spawn(move || {
  log::info!("1: spawn");
  wasm_bindgen_futures::spawn_local(async move {
    log::info!("2: message {:?}", &message);
    while Ok(message) = channel_receiver.recv().await {
      log::info!("3: am i here?");
      download.asset().await;
    }
  })
});
```

I still get nothing (now a tokio channel)

**Comment by felipellrocha** [comment]
This worked: https://github.com/rustwasm/wasm-bindgen/issues/2945 Thanks for the help :D

**Comment by Liamolucko** [comment]
For the record, that is quite a hacky solution; I think it'd be better if `wasm_thread` were to support async entrypoints, since there isn't currently any way to yield from the blocking entrypoint without shutting down the worker.

**Comment by chemicstry** [comment]
Closing this and tracking async entrypoints in #10
